version: '3'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    depends_on:
      - node-app
      - postgres-db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.nodeapp
    networks:
      - app-network

  postgres-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
